url:
  base: http://www.fotocasa.es
  path: /es/alquiler/casas/{zone}/todas-las-zonas/l

zones:
  palma: palma-de-mallorca
  esporles: esporles
  valldemossa: valldemossa
  bunyola: bunyola
  santa_maria: santa-maria-del-cami

filters:
  palma:
    min_price: 400
    max_price: 750
    min_rooms: 2